name: Deploy all

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: '18' }

      - name: Build Store TheBrothersToys
        working-directory: ./store_tbt
        run: |
          npm ci
          npm run build

      - name: Build admin TheBrothersToys
        working-directory: ./admin_tbt
        run: |
          npm ci
          npm run build

      - name: Configure gcloud
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud config set project ${{ vars.GCP_PROJECT }}
          gcloud auth configure-docker --quiet

#      - name: Build & push API image
#        working-directory: ./api_tbt
#        run: |
#          IMAGE=gcr.io/${{ vars.GCP_PROJECT }}/api-tbt:${{ github.sha }}
#          docker build -t $IMAGE .
#          docker push $IMAGE

#      - name: Deploy Cloud Run
#        run: |
#          IMAGE=gcr.io/${{ vars.GCP_PROJECT }}/api-tbt:${{ github.sha }}
#          gcloud run deploy api_tbt \
#            --image $IMAGE \
#            --region ${{ vars.REGION }} \
#            --platform managed \
#            --allow-unauthenticated
#

      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: Deploy Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
        run: |
          firebase use ${{ vars.GCP_PROJECT }}
          firebase deploy --only hosting:${{ vars.FIREBASE_SITE_STORE_TBT }},hosting:${{ vars.FIREBASE_SITE_ADMIN_TBT }} --project ${{ vars.GCP_PROJECT }}